# AETERNUS OS — pacman.conf
# Repositórios: Arch oficial + BlackArch

[options]
HoldPkg      = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 16
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
CleanMethod = KeepCurrent
Color
VerbosePkgLists
ILoveCandy

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[blackarch]
SigLevel = Optional TrustAll
Server = https://mirror.cyberbits.eu/blackarch/$repo/os/$arch
Server = https://www.blackarch.org/blackarch/$repo/os/$arch
Server = https://blackarch.unixpeople.org/$repo/os/$arch
Server = https://blackarch.mirror.munsternet.eu/$repo/os/$arch
Server = https://mirrors.dotsrc.org/blackarch/$repo/os/$arch
