# V0rtexOS — mkinitcpio.conf para linux-hardened
# Caminho: /etc/mkinitcpio.conf
# Aplique com: sudo mkinitcpio -p linux-hardened

# Módulos a incluir na initramfs (apenas o necessário)
MODULES=(ext4 dm_crypt dm_mod cryptd)

# Binários adicionais na initramfs
BINARIES=()

# Arquivos adicionais
FILES=()

# HOOKS — Ordem importante!
# encrypt deve vir antes de filesystems se usar LUKS
HOOKS=(base udev microcode archiso block keyboard keymap consolefont filesystems)

# Compressão da initramfs
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-9)
