name: Build AETERNUS OS ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    env:
      TERM: xterm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm archiso git base-devel libisoburn squashfs-tools dosfstools mtools

      - name: Prepare AETERNUS Build
        working-directory: ./aeternus-os
        run: |
          # Dá permissão aos scripts
          chmod +x build.sh
          chmod +x tools/install-tools.sh
          
          # Entra em tools para rodar o instalador e volta
          cd tools && ./install-tools.sh && cd ..
          
          # Limpa resíduos de builds anteriores
          rm -rf work/
          
      - name: Run Build Script
        working-directory: ./aeternus-os
        run: |
          ./build.sh

      - name: Generate Checksum
        working-directory: ./aeternus-os
        if: always()
        run: |
          mkdir -p release
          cd release/
          sha256sum *.iso > checksum.txt || echo "Nenhuma ISO gerada"

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Aeternus-OS-ISO
          path: |
            aeternus-os/release/*.iso
            aeternus-os/release/checksum.txt
          retention-days: 5
          
